### ISSUE TITLE
Merging Data

### ISSUE THREAD

**Issue by nexflo** [70kft/craft-golive#1]
Anything like migrations or merging data planned? (i.e. not overwriting content?)

**Comment by ktbartholomew** [comment]
@nexflo This would require identifying changes between and merging rows in several tables in the database, all while preserving foreign key constraints and correctly deciding which row being merged has the "correct" data. Entire products have been built to solve this same problem, and it's not one that I intend to re-solve in this plugin.

You **do** have the ability to omit certain tables from being pushed to production.  The most common use case for this is when you have a plugin or other custom code that saves user activity as a custom record in its own table (for example, one of my projects stores records of users' access to gated content).  Excluding this table from the Go Live process will ensure that you don't erase data that's being generated by users.

If you have content editors with CP access and you're trying to merge their changes with your staging site, the best approach would be to convince them (or forcibly prevent them) from using the CP in production. If everyone makes their changes in staging first, the world will be a better place! :wink:
